log-level: info
architecture: amd64
package:
  create: 
    max_package_size: "1000000000"
    set:
      bigbang_version: "2.5.0"
      flux_version: "0.41.2"
  deploy:
    set:
      domain: agreene.dev
      key_file: agreene.dev.key
      cert_file: agreene.dev.cert
      host_path: "/var/lib/rancher/k3s/storage/*"