name: Build and Test Package

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: free-disk-space
      run: rm -rf /opt/hostedtoolcache
      
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Registry1
      uses: docker/login-action@v2
      with:
        registry: registry1.dso.mil
        username: ${{ secrets.REGISTRY1_USERNAME }}
        password: ${{ secrets.REGISTRY1_PASSWORD }}
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        version: v0.29.2
    - name: Build Package
      run: make build
