name: Publish Package

on:
  pull_request:
    types:
      - opened
      - synchronize
  release:
    types: [ "published" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Registry1
      uses: docker/login-action@v2
      with:
        registry: registry1.dso.mil
        username: ${{ secrets.REGISTRY1_USERNAME }}
        password: ${{ secrets.REGISTRY1_PASSWORD }}
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        version: v0.28.1
    - name: Build Package
      run: make build
    - name: Publish Package
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/bobsled-dev/packages 
