name: Publish Package

on:
  push:
    branches: [ "main" ]
  release:
    types: [ "published" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        version: v0.27.0
    - name: Build Package
      run: make build
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: dummy
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Package
      run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/bobsled-dev/packages 
