name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: free-disk-space
      run: rm -rf /opt/hostedtoolcache
    
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to Registry1
      uses: docker/login-action@v2
      with:
        registry: registry1.dso.mil
        username: ${{ secrets.REGISTRY1_USERNAME }}
        password: ${{ secrets.REGISTRY1_PASSWORD }}
    
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        version: v0.29.2
    
    - name: Build Package
      run: make build

    - name: Get Zarf Artifacts
      run: make get-zarf-artifacts
      
    - name: Publish Package
      run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/bobsled-dev/packages 

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/zarf
          build/zarf-init-amd64-*.tar.zst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
